- name: Enable web app's diagnostic logs
  tasks:
    - name: Create diagnostic setting for webapp with event hub and log analytics 
      azure_rm_monitordiagnosticsetting:
        name: "webapp-logs"

        resource:
          name: "ricingOnlineWebApp"
          type: "Microsoft.Web/sites"
          resource_group: "ricingOnlineRG"

        event_hub:
          namespace: "my-event-hub"
          policy: "RootManageSharedAccessKey"

        log_analytics:
          name: "log-analytics-ricingOnline"
          resource_group: "ricingOnlineRG"

        client_id: "{{ lookup('env', 'AZURE_CLIENT_ID') }}"
        secret: "{{ lookup('env', 'AZURE_CLIENT_SECRET') }}"
        tenant: "{{ lookup('env', 'AZURE_TENANT_ID') }}"
        subscription_id: "{{ lookup('env', 'AZURE_SUBSCRIPTION_ID') }}"
