- hosts: localhost
  tasks:
    - name: Create diagnostic setting for webapp with event hub and log analytics 
      azure.azcollection.azure_rm_monitordiagnosticsetting:
        name: "webapp-logs"

        resource:
          name: "webapp-ricingOnline"
          type: "Microsoft.Web/sites"
          resource_group: "ricingOnlineRG"

        event_hub:
          namespace: "my-event-hub"
          policy: "RootManageSharedAccessKey"

        log_analytics:
          name: "log-analytics-ricingOnline"
          resource_group: "ricingOnlineRG"

        logs:
              - category: "AppServiceHTTPLogs"
              - category: "AppServiceConsoleLogs"
              - category: "AppServiceAppLogs"
              - category: "AppServiceAuditLogs"
              - category: "AppServiceIPSecAuditLogs"
              - category: "AppServicePlatformLogs"

        client_id: "{{ lookup('env', 'AZURE_CLIENT_ID') }}"
        secret: "{{ lookup('env', 'AZURE_CLIENT_SECRET') }}"
        tenant: "{{ lookup('env', 'AZURE_TENANT_ID') }}"
        subscription_id: "{{ lookup('env', 'AZURE_SUBSCRIPTION_ID') }}"
