name: Deploy to Azure

on:
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      # As we do not use the build-push-action, we need to expose a few GitHub runtime variables
      # so that the GHA Docker cache works. See https://github.com/moby/buildkit#github-actions-cache-experimental
      - name: Expose GitHub Runtime
        uses: crazy-max/ghaction-github-runtime@v2

      - name: Install Ansible and collections dependencies
        run: |
          python3 -m pip install --upgrade pip
          python -m venv venv
          . venv/bin/activate
          pip3 install ansible packaging requests[security] xmltodict msgraph-sdk==1.0.0 azure-cli-core==2.34.0 azure-common==1.1.11 azure-identity==1.14.0 azure-mgmt-authorization==2.0.0 azure-mgmt-apimanagement==3.0.0 azure-mgmt-batch==16.2.0 azure-mgmt-cdn==11.0.0 azure-mgmt-compute==26.1.0 azure-mgmt-containerinstance==9.0.0 azure-mgmt-core==1.3.0 azure-mgmt-containerregistry==9.1.0 azure-containerregistry==1.1.0 azure-mgmt-containerservice==20.0.0 azure-mgmt-datalake-store==1.0.0 azure-mgmt-datafactory==2.0.0 azure-mgmt-dns==8.0.0 azure-mgmt-marketplaceordering==1.1.0 azure-mgmt-monitor==3.0.0 azure-mgmt-managedservices==6.0.0 azure-mgmt-managementgroups==1.0.0 azure-mgmt-network==19.1.0 azure-mgmt-nspkg==2.0.0 azure-mgmt-privatedns==1.0.0 azure-mgmt-redis==13.0.0 azure-mgmt-resource==21.1.0 azure-mgmt-rdbms==10.0.0 azure-mgmt-search==8.0.0 azure-mgmt-servicebus==7.1.0 azure-mgmt-sql==3.0.1 azure-mgmt-storage==19.0.0 azure-mgmt-trafficmanager==1.0.0b1 azure-mgmt-web==6.1.0 azure-nspkg==2.0.0 azure-storage-blob==12.11.0 azure-core==1.28.0 azure-keyvault==4.2.0 azure-mgmt-keyvault==10.0.0 azure-mgmt-cosmosdb==6.4.0 azure-mgmt-hdinsight==9.0.0 azure-mgmt-devtestlabs==9.0.0 azure-mgmt-loganalytics==12.0.0 azure-mgmt-automation==1.0.0 azure-mgmt-iothub==2.2.0 azure-iot-hub==2.6.1 azure-mgmt-recoveryservices==2.0.0 azure-mgmt-recoveryservicesbackup==3.0.0 azure-mgmt-notificationhubs==7.0.0 azure-mgmt-eventhub==10.1.0 setuptools
          ansible-galaxy collection install azure.azcollection 

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.5.0"

      - uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

      - name: Build dist
        run: ./build-dist.sh


      - run: terraform -chdir="./terraform" init && terraform -chdir="./terraform" validate && terraform -chdir="./terraform" plan
        env:
          TF_VAR_client_id: ${{ secrets.AZURE_CLIENT_ID }}
          TF_VAR_client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          TF_VAR_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          TF_VAR_tenant_id: ${{ secrets.AZURE_TENANT_ID }}

      - run: terraform -chdir="./terraform" apply -auto-approve
        env:
          TF_VAR_client_id: ${{ secrets.AZURE_CLIENT_ID }}
          TF_VAR_client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          TF_VAR_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          TF_VAR_tenant_id: ${{ secrets.AZURE_TENANT_ID }}

      - name: Run Ansible
        run: |
          . venv/bin/activate
          ansible-playbook ansible/enable_logs.yml
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - uses: azure/webapps-deploy@v2
        with:
          app-name: "webapp-ricingOnline"
          slot-name: "production"
          package: "dist"
