name: Jest
on: 
  pull_request: {}
  push:
    branches:
      - main

jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install dependencies
        run: npm install && sudo apt install awesome
      
      - name: Run jest
        run: npm run test
