name: Jest
on: pull_request
jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Run tests
        run: |
          npm install && sudo apt install awesome
          npm run test
