name: Jest
on: pull_request
jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install dependencies
        run: npm install && apt install awesome
      
      - name: test
        run: npm run test
